### ISSUE TITLE
App size

### ISSUE THREAD

**Issue by VasilisKos** [elastic-rock/KeepScreenOn#1]
This is really a very nice, simple, and functional app, but since it doesn't have any complicated UI or settings, why does it have such a big size when installed? More than 18MB, while a non-open source one that I use, with lots of customization options, takes only half the size. It's this one:
[https://play.google.com/store/apps/details?id=com.sapphire_project.screenwidget&hl=en_US](url)

**Comment by elastic-rock** [comment]
Indeed, I did not notice before publishing. However, I am not able to quickly find the cause so I'll keep working on it. Thank you.

**Comment by elastic-rock** [comment]
I set minifyEnabled to true in 1.2.0. Does it fix the issue or not?

**Comment by VasilisKos** [comment]
> I set minifyEnabled to true in 1.2.0. Does it fix the issue or not?

Perfect! Installed size now down to 2.47 MB! 😁
But why are you asking? Can't you check in your device?

**Comment by elastic-rock** [comment]
Of course I checked it on my own, but I want to be sure that it's not just me. :)

**Comment by VasilisKos** [comment]
> Of course I checked it on my own, but I want to be sure that it's not just me. :)

The app is just PERFECT now! Exactly what I've been looking for, for a long time! There's nothing that needs to be touched in it, except the "Never" string. 😉
