### ISSUE TITLE
not working in realme 7 running Android 12

### ISSUE THREAD

**Issue by AntarCrypto** [elastic-rock/KeepScreenOn#12]
I gave all the necessary permission but it doesn't work in my device,can you make it to work with shizuku may be this adb will make it work I don't know.

**Comment by elastic-rock** [comment]
Forgive me, but I do not understand your problem. Does the tile not change state? Is the previous value not restored?

**Comment by AntarCrypto** [comment]
why are you apologizing it's not your fault.I tried many apps from play store for screen timeout tile none of them worked.it's manufacturers problem.I am suggesting if you can make it to work through adb command instead of system settings permission.

**Comment by VasilisKos** [comment]
> I gave all the necessary permission but it doesn't work in my device,can you make it to work with shizuku may be this adb will make it work I don't know.

Disable battery optimization for the app.

**Comment by elastic-rock** [comment]
Adb commands are sent from another device to facilitate app development and cannot be sent from the same device without rooting it. They are not meant to be used in production and cannot be on devices that don't have a compromised security model. In other words, adb commands are not the solution.

**Comment by elastic-rock** [comment]
I would otherwise like to know what specifically doesn't work? Does the tile not change state? Is the previous value not restored? Is the issue on the app itself?

**Comment by AntarCrypto** [comment]
it's doesn't change anything.After press it shows that it worked but after opening the notification bar again it showing its off

**Comment by Gaxi2** [comment]
I am facing the same issue.

**Comment by elastic-rock** [comment]
I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.

P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

**Comment by AntarCrypto** [comment]
> I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.
> 
> P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

**Comment by AntarCrypto** [comment]
> I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.
> 
> P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

where should I upload the video?
and if the lable is current screen timeout then it does change but only when I am inside the app and click the tile and if I close the app and open it again it again goes back to 30k value

**Comment by elastic-rock** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by AntarCrypto** [comment]
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files


Uploading InShot_20231007_140403343.mp4…

**Comment by AntarCrypto** [comment]
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files


https://github.com/elastic-rock/KeepScreenOn/assets/135796323/8fe0a2e0-1820-4721-a049-55f52c9311c2

**Comment by elastic-rock** [comment]
![dialog](https://github.com/elastic-rock/KeepScreenOn/assets/110714645/b466e8ac-970b-44a1-abac-015b6ae575fc)

Version 1.12.0 includes a new option to set the maximum screen timeout. In your case, set 1800000.
