### ISSUE TITLE
Suggestion: A notification for better control

### ISSUE THREAD

**Issue by NikunjKhangwal** [elastic-rock/KeepScreenOn#19]
Personally i think the app should show a notification with a turn off button, all the other similar apps I've used does this. I find it more easy than swiping through quick tiles to turn the service off. Please consider adding it if possible. Thank you

**Comment by NikunjKhangwal** [comment]
Also the icon sometimes take two clicks to turn off, not sure why. It doesn't happen with other apps

**Comment by elastic-rock** [comment]
The button is definitely something worth adding. Can you otherwise specify which icon takes two clicks to turn off?

**Comment by NikunjKhangwal** [comment]
The KeepScreenOn quick setting tile

**Comment by elastic-rock** [comment]
The two click issue will be followed in #20
