### ISSUE TITLE
OPINION WANTED: Tile activation indication

### ISSUE THREAD

**Issue by VasilisKos** [elastic-rock/KeepScreenOn#2]
I think the active indication of the tile should be reversed. What I mean is that, when the app is not "active" the screen timeout is the one set by the user; the default one. In that case the tile should not be lit. When it's tapped, the app is "activated" (infinite timeout), so the tile should be lit. That makes more sense, and it's the way all other respective apps' tiles work.

**Comment by elastic-rock** [comment]
I haven't thought about such an approach. I agree it would probably be easier for people to understand. I am definitely considering it but I will ask around and wait to see if others have anything to say. Thank you very much.

**Comment by elastic-rock** [comment]
I decided quite quickly in the end. :upside_down_face: Will go in the next release.

https://github.com/elastic-rock/KeepScreenOn/commit/34ff2f396e32b6f7539bdb24c910db473b8bd812 #

**Comment by VasilisKos** [comment]
I was afraid of that when I saw the code you removed from the app.
What I meant in my initial report was that the color indication of the tile should be reversed. Just that. Nothing more or less.
It was better when the text of the tile included the default timeout (like 1 minute e. g.), instead of just "Inactive". That was a quick way to check the timeout, without entering the Android settings.
Can you please bring it back?

**Comment by elastic-rock** [comment]
I brought the subtitle back. It is just a temporary fix for the time being. I'm looking for something with which I will be more content.

**Comment by VasilisKos** [comment]
> I brought the subtitle back. It is just a temporary fix for the time being. I'm looking for something with which I will be more content.

I think it's perfect now! The only thing to be changed is the "Never" string to be changed to "Always". Makes more sense: Keep Screen On > Always. 😉

**Comment by elastic-rock** [comment]
> > I brought the subtitle back. It is just a temporary fix for the time being. I'm looking for something with which I will be more content.
> 
> I think it's perfect now! The only thing to be changed is the "Never" string to be changed to "Always". Makes more sense: Keep Screen On > Always. 😉

Makes sense. I'll see in the future.

**Comment by elastic-rock** [comment]
I honestly have to acknowledge that you are right. :upside_down_face:
https://github.com/elastic-rock/KeepScreenOn/commit/c1e224d0d597e8677eeb80248ae7ac1705567767
