### ISSUE TITLE
Can't update to 1.17.0

### ISSUE THREAD

**Issue by GenericMale** [elastic-rock/KeepScreenOn#21]
Looks like versionCode was set to 2 instead of 24 by accident in https://github.com/elastic-rock/KeepScreenOn/commit/3453ea6a4694a9af9c6cc6f144cff49125abcaa4, so Android thinks a newer version is already installed when trying to update from 1.16.2 to 1.17.0

**Comment by elastic-rock** [comment]
Thank you very much for pointing it out. 😅
