### ISSUE TITLE
Version 1.1 safety issue

### ISSUE THREAD

**Issue by VasilisKos** [elastic-rock/KeepScreenOn#5]
When I installed the new 1.1 version, I got a warning from Play Protect. That didn't happen with 1.0. Can you check this? Maybe it has to do with the apk signature or something. 

P. S. I hope the app size issue is soon fixed. 😊

**Comment by elastic-rock** [comment]
The signature seems to be fine. I guess Google might have already gotten the 1.0.0 version before you installed it and therefore didn't flag it bug might not have gotten the 1.1.0 version and flagged it as a result.
