### ISSUE TITLE
Tile not changing state on Oppo a16

### ISSUE THREAD

**Issue by xjanno** [elastic-rock/KeepScreenOn#7]
I give the permission to the app that is needed but when I turn on the button it doesn't work and it turns off. my phone is oppo a16,

**Comment by VasilisKos** [comment]
> I give the permission to the app that is needed but when I turn on the button it doesn't work and it turns off. my phone is oppo a16,

Try disabling battery optimization for the app. All those Chinese companies are known for their aggressive battery policies.

**Comment by elastic-rock** [comment]
I will try and look into it but I haven't encountered such an issue on my device.

**Comment by elastic-rock** [comment]
To identify the issue, I would need the system log. Here is a link to a guide I found online, but I'm sure you can find others yourself.

https://www.xda-developers.com/how-to-take-logs-android/

**Comment by elastic-rock** [comment]
I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.

P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

**Comment by eikaramba** [comment]
I observed the same problem on my one plus 8t. However when I entered the maximum value(1800000) from the settings into this app as the maximum value toggling the button works now. So it seems if the maximum value is not supported there is a problem. Btw I used to use tasker for this but unfortunately it does not work anymore. I don't know why. So happy to have found this app

**Comment by eikaramba** [comment]
thankfully to your sourcecode i was able to replicate the same behaviour with tasker now. the trick was to not use the predefined action for display timeout but instead use the general settings action, and then use "system" and "screen_off_timeout" - will however use your app for now as it is more convenient

**Comment by elastic-rock** [comment]
@eikaramba, I am happy that the app is of use to you and that you were able to solve the problem. Based on your comment and the initial comment of @xjanno, I believe that the same issue is happening on the Oppo and will, therefore, close this issue.
