### ISSUE TITLE
Low battery deactivation

### ISSUE THREAD

**Issue by Markus40** [elastic-rock/KeepScreenOn#9]
There is a risk of forgetting to reactivate the timeout and draining the battery overnight.

A customizable minimum battery level could re-enable the timeout when the device drops below that level. If the timeout is disabled again below this level, it could work as normal and drain the device until it is empty.

**Comment by elastic-rock** [comment]
Thank you for your suggestion. The scenario of draining the battery can only happen if the screen is left on. Whilst I know people that leave their phone behind with the screen on, it is an immense risk from a security standpoint, as the device is left unlocked for anyone to tamper with. For this reason, I will still think about it.

**Comment by elastic-rock** [comment]
To be able to set the the percentage at which the timeout would be disabled, the app would have to periodically monitor the battery state in the background, which would have a negative effect on battery life. It would be better to implement the feature as "restore timeout when battery low", meaning the timeout would be restored when the system notifies the app, which it can do when it drops below warning level (20% on most devices). I have worked on this implementation and plan on releasing it after further testing and app UI redesign.
